### ISSUE TITLE
editing Contributing.md

### ISSUE THREAD

**Issue by kfoofw** [UBC-MDS/rsketball#7]
Some guidelines:

https://github.com/swcarpentry/r-novice-inflammation/blob/gh-pages/CONTRIBUTING.md

https://github.com/thoughtbot/factory_bot_rails/blob/master/CONTRIBUTING.md

https://github.com/moby/moby/blob/master/CONTRIBUTING.md

**Comment by kfoofw** [comment]
to just upload the same Contributing document from `pysketball`

**Comment by vanandsh** [comment]
Edited
